config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'home', to: 'pages#home'
  root to: redirect('/home')
  get 'about', to: 'pages#about'
  get 'work', to: 'pages#work'
  get 'contact', to: 'pages#contact'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    render :home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevPortfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>       
<link rel="stylesheet" href="<%= asset_path('problem3.css') %>">
<title>About Page</title>
</head>
<body>
    
    <%= link_to "Home", root_path, class: "btn btn-primary" %>
    <%= link_to "work", work_path, class: "btn btn-primary" %>
    <%= link_to "contact", contact_path, class: "btn btn-primary" %>

<h1>About Me</h1>
<div class="container">

<h2>Name:</h2> <p>Vivian</p>
<h2>Profession:</h2> <p>Aspiring Software Developer</p>
<h2>Languages:</h2> <p>JS, 
                        Python,
                        C/C++,
                        SQL,
                        Ruby</p>

<h2>Education Background:</h2> <p>Current Junior at the University of Memphis studying Computer Science with an interest in a Master's Degree in Computer Science.
</p>

<h2>Classes:</h2> <p>Intro to Programming,
                    Intro to Software Engineering,
                    Software Engineering,
                    Computer Architecture,
                    Operating Systems</p>
<h2>Conclusion:</h2> <p>As I continue throughout my major, I am developing various websites to interest people in different groups.
As a student, I am a dynamic and motivated individual with a bright future ahead in the field of software development. 
</p>

</div>

</body>
</html>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="<%= asset_path('problem3.css') %>">
<title>My Contact</title>
</head>
<body>
<%= link_to "Home", root_path, class: "btn btn-primary" %>
    <%= link_to "work", work_path, class: "btn btn-primary" %>
    <%= link_to "about", about_path, class: "btn btn-primary" %>
    <h1>Contact Information</h1>
<div class="container3">
    <div class="container2">
        <h2>Name:</h2><p>Vivian Ly</p>
        <h2>Email:</h2><p>vivian@gmail.com</p>
        <h2>Phone Number:</h2><p>(901)123-4567</p>
        <h2>School:</h2><p>University of Memphis</p>
    </div>
</div>

</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Vivian's Web Developer</title>
<link rel="stylesheet" href="<%= asset_path('problem2.css') %>">
</head>

<div >
    <%= link_to "about", about_path, class: "btn btn-primary" %>
    <%= link_to "work", work_path, class: "btn btn-primary" %>
    <%= link_to "contact", contact_path, class: "btn btn-primary" %>
</div>
<body>
    <h1>Web Developer
        ~~~~~~~~~~~~~~~~~~~~~~~</h1>
    <h2>Focus on STEM
        ~~~~~~~~~~~~~~~~~~~~~~~ Code Development~~~~~~~~~~~~~~~~~~~~~~~
        Design Development~~~~~~~~~~~~</h2>

<div class="container3">
    <div class="container2">
    <p >
        Hello, I am a beginner coder interested in the various STEM related subjects. I want to explore interests within gaming, website development, and designing websites as well. I hope to find more people interested within web development to continue further developing the projects I create!
    </p>
    </div>
</div>
</body>
</html>

app/views/pages/work.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="<%= asset_path('problem3.css') %>">
<title>Work</title>
</head>
<body>
    <%= link_to "Home", root_path, class: "btn btn-primary" %>
    <%= link_to "about", about_path, class: "btn btn-primary" %>
    <%= link_to "contact", contact_path, class: "btn btn-primary" %>
    <h1>Work: My Projects</h1>

<h2>Project 1: Recipe website through Github Pages</h2>
<h3>Description:
    Using html and js, I have implemented these to create a webpage to toggle between ingredients for a seamless and easy to use website for recipes.
</h3>
<p></p>
<div class="images">
    <%= image_tag "image2.png", class: "images" %>
    <%= image_tag "image1.png", class: "images" %>
</div>


<h2>Project 2: Menu</h2>
<h3>Description:
    The use of CSS is important in website development. Here is an example of a menu created with html and css.
</h3>
<p></p>
<div class="images">
    <%= image_tag "image3.png", class: "images" %>
</div>

</body>
</html>